An all ones tensor

In [1]:
import tensorflow as tf
x = tf.ones(shape = (2 , 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
x = tf.random.normal(shape = (3, 1), mean = 0., stddev = 1.)
print(x)

tf.Tensor(
[[-0.08539372]
 [-1.2094401 ]
 [-0.8758951 ]], shape=(3, 1), dtype=float32)


With numpy you can assign arrays, whereas with tensorflow that is not possible.

In [5]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0

To update a state in tensorflow, variables will be used.

In [6]:
v = tf.Variable(initial_value=tf.random.normal(shape = (3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.903623 ],
       [0.6190442],
       [1.3250747]], dtype=float32)>


Now this state can be moddified with ```assign```.

In [8]:
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>